### PR TITLE
AI Work

### PR DESCRIPTION
**Pull request by KPDwyer**
//AI Steps
//Real Dumb AI - follows strict list of connect nodes.
//Better AI - can determine optimal set of nodes between 2 points (A*)
//Best AI - stops if a car is in the way
//Godlike AI - won't turn into the side of another car

### CODE REVIEW

**Comment by KPDwyer** [comment]
Real Dumb AI is ready

**Comment by KPDwyer** [comment]
authoring road nodes is time consuming.  potential solution:
AutoNode - editor side function
1-search road tilemap for 3x3 plain road tiles (tech restraint exerts opinion on design, not great)
2-for each appearance of this pattern,
             a - place nodes in each corner.
             b - connect corner nodes
3 - for every node on the map,  do a line of sight test for every other node on the map within distance threshold
             -can you do a physics raycast in editor script?

will want to flag auto nodes as auto (vs manual) for the sake of rebuilding while maintaining hand-placed nodes.

**Comment by KPDwyer** [comment]
Better AI Implemented.  

Automatic connection of hand-placed waypoints complete.  going to merge this for now and get actual game stuff working before getting too deep in the AI

**Comment by TannerRogalsky** [comment]
My inclination is that it would be best to use a nav mesh. Is there a technical constraint keeping you from doing that?

**Comment by KPDwyer** [comment]
I spent some time looking at Unity's Navmesh.  I'm both unfamiliar with the tool and unable to find any obvious answer as to whether or not it works in 2D that is more recent than 2016.  Best most recent find is : https://www.reddit.com/r/Unity3D/comments/64xhrz/implementing_navmesh_56_in_2d_for_a_game_jam/

which I feel means its probably possible but not quite streamlined yet.  also most resources for this stuff are in video format, which means I can't really digest it easily while doing the work (I do all my work for this stuff on a train with a macbook air).

I put in a not-great A* solution, not ideal but fine for a jam and should save @MDEaton a ton of time when he's building the roadmap.

**Pull request merged**
